name: build-windows-dll
on:
  push:
    branches:
      - main
      - production
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: 'Build DLL'
      run: |
        ./build-scripts/android.ps1
        ./build-scripts/windows-64.ps1
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: windows-64-release
        path: cgamelink.dll
        retention-days: 2
