name: build-windows-dll
on:
  push:
    branches:
      - main
      - production
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: 'Build DLL'
      run: |
        mkdir build
        cd build
        cmake -Ax64 ../gamelink-cpp
        cmake --build . --target cgamelink --config Release --parallel 8
        copy "Release\cgamelink.dll" ..
        cd ..
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: windows-64-release
        path: cgamelink.dll
        retention-days: 2